-- ============================================================================
-- GearSync - TurtleLootLine Addon
-- Syncs equipped gear to desktop companion and displays upgrade recommendations
-- ============================================================================

-- Saved data (written to WTF folder)
GearSyncData = GearSyncData or {}

-- Upgrade data (generated by Electron companion)
GearSyncUpgrades = GearSyncUpgrades or {}

-- Slot IDs to slot names mapping
local SLOT_NAMES = {
    [1] = "Head",
    [2] = "Neck",
    [3] = "Shoulder",
    [4] = "Shirt",
    [5] = "Chest",
    [6] = "Waist",
    [7] = "Legs",
    [8] = "Feet",
    [9] = "Wrist",
    [10] = "Hands",
    [11] = "Finger1",
    [12] = "Finger2",
    [13] = "Trinket1",
    [14] = "Trinket2",
    [15] = "Back",
    [16] = "MainHand",
    [17] = "OffHand",
    [18] = "Ranged",
    [19] = "Tabard"
}

-- Create main event frame
local frame = CreateFrame("Frame")

-- ============================================================================
-- UTILITY FUNCTIONS
-- ============================================================================

local function Print(msg)
    DEFAULT_CHAT_FRAME:AddMessage("|cFF00FF00[GearSync]|r " .. msg)
end

local function PrintError(msg)
    DEFAULT_CHAT_FRAME:AddMessage("|cFFFF0000[GearSync]|r " .. msg)
end

-- ============================================================================
-- EQUIPMENT SCANNING
-- ============================================================================

-- Extract item name from item link
local function GetItemNameFromLink(itemLink)
    if not itemLink or type(itemLink) ~= "string" or itemLink == "" then
        return nil
    end

    -- Item link format: |cXXXXXXXX|Hitem:id:...|h[Item Name]|h|r
    local _, _, itemName = string.find(itemLink, "%[(.+)%]")
    return itemName
end

-- Scan all equipped gear and return equipment table
local function ScanEquipment()
    local equipment = {}

    for slotId = 1, 19 do
        local itemLink = GetInventoryItemLink("player", slotId)

        if itemLink then
            local _, _, itemIdStr = string.find(itemLink, "item:(%d+)")
            local itemId = tonumber(itemIdStr)

            -- Extract name from link (more reliable than GetItemInfo in Vanilla)
            local itemName = GetItemNameFromLink(itemLink)

            -- Fallback to GetItemInfo if link parsing failed
            if not itemName then
                itemName = GetItemInfo(itemLink)
            end

            if itemId and itemName then
                equipment[slotId] = {
                    slot = SLOT_NAMES[slotId],
                    itemId = itemId,
                    itemName = itemName,
                    itemLink = itemLink
                }
            end
        end
    end

    return equipment
end

-- ============================================================================
-- DATA PERSISTENCE
-- ============================================================================

-- Throttle SaveData to prevent spam
local lastSaveTime = 0
local SAVE_THROTTLE = 2  -- Only save once per 2 seconds

-- Save current gear data to SavedVariables
local function SaveData(forceDebug)
    -- Throttle to prevent excessive saves
    local currentTime = time()
    if currentTime - lastSaveTime < SAVE_THROTTLE then
        if forceDebug then
            Print("SaveData throttled (wait " .. (SAVE_THROTTLE - (currentTime - lastSaveTime)) .. " seconds)")
        end
        return
    end
    lastSaveTime = currentTime

    local equipment = ScanEquipment()

    GearSyncData = {
        lastUpdated = time(),
        character = UnitName("player"),
        realm = GetRealmName(),
        class = UnitClass("player"),
        equipment = equipment
    }

    -- Debug: count equipped items
    local count = 0
    for _ in pairs(equipment) do
        count = count + 1
    end

    if forceDebug then
        Print(string.format("Saved %d equipped items to GearSyncData", count))
        Print(string.format("Character: %s (%s)", UnitName("player"), GetRealmName()))
    end
end

-- ============================================================================
-- EVENT HANDLERS
-- ============================================================================

-- Main event handler
local function OnEvent()
    if event == "PLAYER_ENTERING_WORLD" then
        -- Player logged in or entered world
        -- Force a save immediately on login (bypass throttle)
        lastSaveTime = 0  -- Reset throttle
        SaveData(true)     -- Enable debug output

        -- Show upgrade count if available
        local upgradeCount = 0
        for _ in pairs(GearSyncUpgrades) do
            upgradeCount = upgradeCount + 1
        end

        if upgradeCount > 0 then
            Print(string.format("Loaded upgrade data for %d items", upgradeCount))
        else
            Print("Tip: Desktop companion will sync upgrade data")
        end

    elseif event == "UNIT_INVENTORY_CHANGED" then
        -- Inventory changed (includes equipment changes in Vanilla)
        local unit = arg1
        if unit == "player" then
            SaveData()
        end
    end
end

frame:SetScript("OnEvent", OnEvent)

-- Register events (Vanilla 1.12 compatible)
frame:RegisterEvent("PLAYER_ENTERING_WORLD")
frame:RegisterEvent("UNIT_INVENTORY_CHANGED")

-- ============================================================================
-- TOOLTIP HOOK FOR UPGRADE DISPLAY
-- ============================================================================

-- Get color code for stat change
local function GetStatColor(value)
    if not value then return "|cFFFFFFFF" end

    local str = tostring(value)
    if string.sub(str, 1, 1) == "+" then
        return "|cFF00FF00"  -- Green for positive
    elseif string.sub(str, 1, 1) == "-" then
        return "|cFFFF0000"  -- Red for negative
    else
        return "|cFFFFFFFF"  -- White for neutral
    end
end

-- Format stat name for display
local function FormatStatName(statKey)
    if not statKey or type(statKey) ~= "string" then
        return "Unknown"
    end

    -- Convert camelCase to readable format
    local formatted = string.gsub(statKey, "([a-z])([A-Z])", "%1 %2")
    -- Capitalize first letter
    return string.upper(string.sub(formatted, 1, 1)) .. string.sub(formatted, 2)
end

-- Track current tooltip item link (vanilla 1.12 has no tooltip:GetItem())
local currentTooltipItemLink = nil
local lastTooltipItem = nil

-- Hook a tooltip method: call original, then store the item link via linkGetter
local function HookTooltipSetMethod(tooltip, methodName, linkGetter)
    local original = tooltip[methodName]
    if not original then return end
    tooltip[methodName] = function(self, a1, a2, a3)
        original(self, a1, a2, a3)
        currentTooltipItemLink = linkGetter(a1, a2, a3)
    end
end

-- Hook GameTooltip item-setting methods to capture the item link
HookTooltipSetMethod(GameTooltip, "SetBagItem", function(bag, slot)
    return GetContainerItemLink(bag, slot)
end)

HookTooltipSetMethod(GameTooltip, "SetInventoryItem", function(unit, slot)
    return GetInventoryItemLink(unit, slot)
end)

HookTooltipSetMethod(GameTooltip, "SetLootItem", function(slot)
    return GetLootSlotLink(slot)
end)

HookTooltipSetMethod(GameTooltip, "SetQuestItem", function(itemType, index)
    if GetQuestItemLink then return GetQuestItemLink(itemType, index) end
    return nil
end)

HookTooltipSetMethod(GameTooltip, "SetQuestLogItem", function(itemType, index)
    if GetQuestLogItemLink then return GetQuestLogItemLink(itemType, index) end
    return nil
end)

HookTooltipSetMethod(GameTooltip, "SetMerchantItem", function(index)
    if GetMerchantItemLink then return GetMerchantItemLink(index) end
    return nil
end)

HookTooltipSetMethod(GameTooltip, "SetCraftItem", function(index, reagent)
    if GetCraftItemLink then return GetCraftItemLink(index) end
    return nil
end)

HookTooltipSetMethod(GameTooltip, "SetTradeSkillItem", function(index, reagent)
    if GetTradeSkillItemLink then return GetTradeSkillItemLink(index) end
    return nil
end)

HookTooltipSetMethod(GameTooltip, "SetHyperlink", function(link)
    if link and string.find(link, "^item:") then
        local _, _, itemId = string.find(link, "item:(%d+)")
        if itemId then
            local name, itemLink = GetItemInfo(tonumber(itemId))
            return itemLink
        end
    end
    return nil
end)

-- Hook ItemRefTooltip for chat link clicks
HookTooltipSetMethod(ItemRefTooltip, "SetHyperlink", function(link)
    if link and string.find(link, "^item:") then
        local _, _, itemId = string.find(link, "item:(%d+)")
        if itemId then
            local name, itemLink = GetItemInfo(tonumber(itemId))
            return itemLink
        end
    end
    return nil
end)

-- Add upgrade data to tooltip
local function AddUpgradeDataToTooltip(tooltip)
    local itemLink = currentTooltipItemLink
    if not itemLink then
        lastTooltipItem = nil
        return
    end

    -- Extract item ID from link
    local _, _, itemIdStr = string.find(itemLink, "item:(%d+)")
    if not itemIdStr then return end

    local itemId = tonumber(itemIdStr)
    if not itemId then return end

    -- Prevent duplicate additions
    if lastTooltipItem == itemId then return end
    lastTooltipItem = itemId

    -- Check if we have upgrade data for this item
    local upgrade = GearSyncUpgrades[itemId]
    if not upgrade then return end

    -- Add separator
    tooltip:AddLine(" ")
    tooltip:AddLine("|cFF00BFFF⚔ TurtleLootLine:|r")

    -- Display stats in order: stamina, armor, strength, agility, etc., then overall
    local statsOrder = {
        "stamina", "armor", "strength", "agility", "intellect", "spirit",
        "defense", "attackPower", "spellPower", "healing", "hitRating",
        "critRating", "hasteRating", "dodgeRating", "parryRating", "blockRating"
    }

    for _, statKey in ipairs(statsOrder) do
        local value = upgrade[statKey]
        if value then
            local color = GetStatColor(value)
            local statName = FormatStatName(statKey)
            tooltip:AddLine("  " .. statName .. ": " .. color .. value .. "|r")
        end
    end

    -- Overall stat (highlighted in gold)
    if upgrade.overall then
        local color = GetStatColor(upgrade.overall)
        tooltip:AddLine("  |cFFFFD700Overall: " .. color .. upgrade.overall .. "|r")
    end

    -- Note (if available)
    if upgrade.note then
        tooltip:AddLine("  |cFFAAAAAA" .. upgrade.note .. "|r")
    end

    -- Refresh tooltip to update size
    tooltip:Show()
end

-- Hook GameTooltip using OnUpdate (Vanilla 1.12 compatible)
local tooltipUpdateDelay = 0
local oldGameTooltipOnUpdate = GameTooltip:GetScript("OnUpdate")

GameTooltip:SetScript("OnUpdate", function()
    -- Call original OnUpdate if it exists
    if oldGameTooltipOnUpdate then
        oldGameTooltipOnUpdate()
    end

    -- Throttle updates to every 0.1 seconds
    tooltipUpdateDelay = tooltipUpdateDelay + arg1
    if tooltipUpdateDelay > 0.1 then
        tooltipUpdateDelay = 0

        -- Check if tooltip is visible and has item data
        if this:IsVisible() then
            AddUpgradeDataToTooltip(this)
        else
            lastTooltipItem = nil
            currentTooltipItemLink = nil
        end
    end
end)

-- Also hook ItemRefTooltip (for chat links)
local itemRefUpdateDelay = 0
local oldItemRefTooltipOnUpdate = ItemRefTooltip:GetScript("OnUpdate")

ItemRefTooltip:SetScript("OnUpdate", function()
    if oldItemRefTooltipOnUpdate then
        oldItemRefTooltipOnUpdate()
    end

    itemRefUpdateDelay = itemRefUpdateDelay + arg1
    if itemRefUpdateDelay > 0.1 then
        itemRefUpdateDelay = 0

        if this:IsVisible() then
            AddUpgradeDataToTooltip(this)
        else
            lastTooltipItem = nil
        end
    end
end)

-- ============================================================================
-- SLASH COMMANDS
-- ============================================================================

local function HandleSlashCommand(msg)
    msg = string.lower(msg or "")

    if msg == "scan" or msg == "s" then
        SaveData(true)  -- Pass true to enable debug output
        Print("Manual scan complete!")

    elseif msg == "stats" or msg == "stat" then
        -- Show statistics
        local equipment = ScanEquipment()
        local equippedCount = 0
        for _ in pairs(equipment) do
            equippedCount = equippedCount + 1
        end

        local upgradeCount = 0
        for _ in pairs(GearSyncUpgrades) do
            upgradeCount = upgradeCount + 1
        end

        Print("--- Statistics ---")
        Print(string.format("Equipped items: %d", equippedCount))
        Print(string.format("Upgrade data loaded: %d items", upgradeCount))

        if GearSyncData.lastUpdated then
            local timeSince = time() - GearSyncData.lastUpdated
            Print(string.format("Last scan: %d seconds ago", timeSince))
        end

    elseif msg == "clear" then
        -- Clear saved data
        GearSyncData = {}
        Print("Saved data cleared")

    elseif msg == "upgrades" then
        -- List items with upgrade data
        Print("--- Items with Upgrade Data ---")
        local count = 0
        for itemId, data in pairs(GearSyncUpgrades) do
            count = count + 1

            -- Ensure itemId is a number
            local numericItemId = tonumber(itemId)
            if not numericItemId then
                Print("Warning: Invalid item ID: " .. tostring(itemId))
            else
                -- Try to get item name, with fallback to ID if not cached
                local itemName = GetItemInfo(numericItemId)
                if not itemName then
                    itemName = "Item #" .. numericItemId
                end

                local overall = data.overall or "N/A"
                Print(string.format("%s: %s", itemName, overall))
            end

            if count >= 10 then
                local totalCount = 0
                for _ in pairs(GearSyncUpgrades) do
                    totalCount = totalCount + 1
                end
                Print(string.format("... and %d more items", totalCount - 10))
                break
            end
        end

        if count == 0 then
            Print("No upgrade data loaded")
        end

    elseif msg == "debug" or msg == "d" then
        -- Show debug information
        Print("--- Debug Information ---")

        if not GearSyncData or not GearSyncData.character then
            Print("|cFFFF0000GearSyncData is empty or not initialized!|r")
            Print("Try running: /gs scan")
        else
            Print(string.format("Character: %s", GearSyncData.character or "nil"))
            Print(string.format("Realm: %s", GearSyncData.realm or "nil"))
            Print(string.format("Class: %s", GearSyncData.class or "nil"))
            Print(string.format("Last Updated: %s", GearSyncData.lastUpdated or "nil"))

            if GearSyncData.equipment then
                local count = 0
                for slotId, item in pairs(GearSyncData.equipment) do
                    count = count + 1
                end
                Print(string.format("Equipment slots: %d", count))

                -- Show first few items as examples
                local shown = 0
                for slotId, item in pairs(GearSyncData.equipment) do
                    if shown < 3 then
                        Print(string.format("  [%d] %s (%s)", slotId, item.itemName or "?", item.slot or "?"))
                        shown = shown + 1
                    end
                end
                if count > 3 then
                    Print(string.format("  ... and %d more items", count - 3))
                end
            else
                Print("|cFFFF0000No equipment data!|r")
            end
        end

    -- [DEBUG] Loot collector commands (remove before release)
    elseif msg == "lootdb" then
        local count = GearSync_GetLootDBCount and GearSync_GetLootDBCount() or 0
        Print("[DEBUG] --- Loot Database ---")
        Print(string.format("Items collected: %d", count))
        Print(string.format("DB version: %s", tostring(GearSyncLootDB.version or "N/A")))
        if GearSyncLootDB.lastUpdated and GearSyncLootDB.lastUpdated > 0 then
            Print(string.format("Last updated: %d seconds ago", time() - GearSyncLootDB.lastUpdated))
        end

    elseif string.find(msg, "^lootitem ") then
        local _, _, idStr = string.find(msg, "^lootitem (%d+)")
        local itemId = tonumber(idStr)
        if not itemId then
            PrintError("Usage: /gs lootitem <itemId>")
        elseif not GearSyncLootDB.items or not GearSyncLootDB.items[itemId] then
            PrintError("Item #" .. itemId .. " not found in loot DB")
        else
            local item = GearSyncLootDB.items[itemId]
            Print("[DEBUG] --- Item #" .. itemId .. " ---")
            Print("Name: " .. (item.name or "?"))
            Print("Quality: " .. tostring(item.quality or "?"))
            Print("Type: " .. (item.itemType or "?") .. " / " .. (item.itemSubType or "?"))
            Print("Slot: " .. (item.equipSlot or "?"))
            Print("Bind: " .. (item.bindType or "?"))
            if item.stats then
                for stat, val in pairs(item.stats) do
                    Print("  " .. stat .. ": " .. tostring(val))
                end
            end
            if item.equip then
                for i = 1, table.getn(item.equip) do
                    Print("  Equip: " .. item.equip[i])
                end
            end
            local sourceCount = item.sources and table.getn(item.sources) or 0
            Print("Sources: " .. sourceCount .. " entries")
        end

    elseif msg == "lootclear" then
        GearSyncLootDB = { version = 1, lastUpdated = 0, items = {} }
        Print("[DEBUG] Loot database cleared")

    elseif msg == "lootpending" then
        local count = GearSync_GetPendingCount and GearSync_GetPendingCount() or 0
        Print("[DEBUG] Pending items in retry queue: " .. count)

    elseif msg == "loottest" then
        -- Parse tooltip of currently hovered item
        local itemLink = currentTooltipItemLink
        if not itemLink then
            PrintError("Hover over an item first")
        else
            local parsed = GearSync_ParseItemTooltip(itemLink)
            if not parsed then
                PrintError("Could not parse item (not cached?)")
            else
                Print("[DEBUG] --- Tooltip Parse ---")
                Print("Name: " .. (parsed.name or "?"))
                Print("Slot: " .. (parsed.equipSlot or "?"))
                Print("Armor Type: " .. (parsed.armorType or "?"))
                Print("Bind: " .. (parsed.bindType or "?"))
                Print("Req Level: " .. tostring(parsed.requiredLevel or "?"))
                if parsed.stats then
                    for stat, val in pairs(parsed.stats) do
                        Print("  " .. stat .. ": " .. tostring(val))
                    end
                end
                if parsed.equip then
                    for i = 1, table.getn(parsed.equip) do
                        Print("  Equip: " .. parsed.equip[i])
                    end
                end
                if parsed.dps then
                    Print("DPS: " .. tostring(parsed.dps))
                end
            end
        end
    -- [/DEBUG]

    elseif msg == "help" or msg == "h" or msg == "?" then
        Print("--- Commands ---")
        Print("/gs scan - Manually scan and save equipped gear")
        Print("/gs stats - Show addon statistics")
        Print("/gs upgrades - List items with upgrade data")
        Print("/gs debug - Show saved data (for troubleshooting)")
        Print("/gs clear - Clear saved data")
        Print("/gs help - Show this help")
        -- [DEBUG] Loot commands (remove before release)
        Print("--- Debug (Loot Collector) ---")
        Print("/gs lootdb - Show loot database stats")
        Print("/gs lootitem <id> - Inspect item in loot DB")
        Print("/gs lootclear - Reset loot database")
        Print("/gs lootpending - Show retry queue size")
        Print("/gs loottest - Parse hovered item tooltip")

    else
        Print("Unknown command. Type /gs help for available commands")
    end
end

-- Register slash commands
SLASH_GEARSYNC1 = "/gs"
SLASH_GEARSYNC2 = "/gearsync"
SlashCmdList["GEARSYNC"] = HandleSlashCommand

-- ============================================================================
-- INITIALIZATION
-- ============================================================================

Print("Loaded! Type /gs help for commands")
